# This workflow will upload a Python Package using UV when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package to PyPi

on:
  release:
    types:
      - published

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install UV
      run: |
        pip install uv
    - name: Build and publish
      env:
        UV_PUBLISH_USERNAME: ${{ secrets.PYPI_USERNAME }}
        UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        make build
        uv publish
